repos:
  - repo: local
    hooks:
      - id: custom-script-file
        name: custom-script-file
        entry: deploy/generate_requirements.sh
        language: script
        types: [python]
        pass_filenames: false